### ISSUE TITLE
Issue with ZonePet files on curseforge?

### ISSUE THREAD

**Issue by tflo** [trozware/ZonePet#1]
Since yesterday I get an error when trying to update my add-ons via [CurseBreaker](https://github.com/AcidWeb/CurseBreaker):

```
RuntimeError: Failed to parse addon data: ZonePet.
The project doesn't have any releases.
```

Manually checking the status with `status ZonePet` yields the same error.

I cannot 100% exclude that it is a CurseBreaker issue, but the fact that ZonePet is the only add-on that produces that error points into the direction that something is wrong with the ZonePet project files on curseforge.
A manual download from curseforge seems to work fine.

Maybe you can check if there is something wrong with ZonePet’s metadata on curseforge? If you don’t find any anomalies, I’ll have to investigate further.

Thanks in advance

– Tom

**Comment by trozware** [comment]
Hi Tom,

Thanks for the report. Checking the data, CurseForge was not publishing the list of latest files for this mod. I could not see why, but I published an update that does nothing new and now it works and CurseBreaker can see the mod and update it.

You might also like to check out my Zone Mount mod which does a similar task only for mounts.
https://www.curseforge.com/wow/addons/zone-mount

Regards,
Axelady

**Comment by tflo** [comment]
Yes, my CurseBreaker also sees it now again. Thank you.

I already use ZoneMount. Though my main mount add-on is [LiteMount](https://www.curseforge.com/wow/addons/litemount), but sometimes when I want to see a mount other than my priority mounts, I press my ZoneMount key.

(LiteMount has some features that are really indispensable for me, like: configurable weighted randomness, and an unrestrictedly configurable core script, which allows me to make it behave exactly as I want. For example for alternate actions like Zen Flight, Running Wild, Sprint, etc., or race/class/char-specific priorities.)

Have a nice day
– Tom
