### ISSUE TITLE
Minimap button: Compatibility with minimap add-ons

### ISSUE THREAD

**Issue by tflo** [trozware/ZonePet#2]
Seems I am the only poster on this issue page ;)

Some time ago I noticed that ZonePet’s minimap button does not play well with [BasicMinimap](https://www.curseforge.com/wow/addons/basic-minimap), and now also not with the new minimap features of [LeatrixPlus](https://www.curseforge.com/wow/addons/leatrix-plus): When moving the button, it moves on a fix circle path, instead of following the real shape of the minimap (for example a square). Probably the same is true with other minimap add-ons, not tested.

According to the author of LeatrixPlus, this is because ZonePet doesn’t use LibDBIcon, unlike most of the other add-ons.

In the context of another issue he posted [a pretty compact solution for this](https://github.com/leatrix/leatrix-plus/issues/71#issuecomment-998347579). I could patch my copy of ZonePet with this, but perhaps you would be interested in putting this in your source to make it available to all users?

– Tom

**Comment by trozware** [comment]
Thanks Tom,

I have updated this add-on now to work correctly with minimap addons.

Thanks for the report. And yes - most people leave a comment on CurseForge instead of coming here.

**Comment by tflo** [comment]
Thank you for the update! Button works fine now with both Leatrix and BasicMinimap.
